project:
  type: book

book:
  title: "Computational Sociology (PGSP11583)"
  author: "Christopher Barrie"
  cover-image: images/cover.png
  repo-url: https://github.com/cjbarrie/CS-ED/
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, linkedin]
  date: today
  chapters:
    - index.qmd
    - course_overview.qmd
    - intro.qmd
    - terminal_and_git.qmd
    - chap1.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual



