# Week 1: Intro. to CSS

This week will be dedicated to a more general introduction to computational social science and what it means to think "computationally."

## Computational data

In essence, this means getting used to different types of data. These might be:

-   Social media data;
-   Image data;
-   Sound data;
-   Video data;
-   Remote sensing data;
-   Call detail records

These data are "found" or "trace" data. They are not custom-made for social science; they *can* be repurposed, though, for answering questions in the social sciences.

## Computational thinking

We'll also be be talking about what it means to "think computationally." In her [article](http://www.cs.cmu.edu/afs/cs/usr/wing/www/publications/Wing06.pdf) Jeanette Wing describes computational thinking as a "universally applicable attitude and skill set everyone, not just computer scientists, would be eager to learn and use." But what is computational thinking?

In summary, it asks:

-   what is computable?;
-   it states the difficulty of a problem in computational terms;
-   it asks whether an approximate solution is good enough;
-   and it requires imagination to abstract into an approximate solution;
-   to problems that might apply across almost every academic discipline imaginable

We'll discuss a concrete example of this in our lecture.

## Essential reading:

-   @salganik_bit_2017

-   @lazer_computational_2020

-   @lazer_meaningful_2021

-   @wing_computational_2006

## Slides

Slides for week one are available [here](https://raw.githack.com/cjbarrie/CS-ED/main/slides/001_intro.html)
