# Week 3: Web tracking and networks

Last week we discussed the question of online "echo chambers" or "filter bubbles." For this, we encountered a number of articles employing new computational tools to study these dynamics.

One of these tools was web-tracking---a subject we will discuss in detail this week. We will walk through the steps for generating web-tracking data and also unpack what web-tracking data looks like. We will then be thinking about what problems these techniques solve and which they fail to answer.

A new type of analysis, which we didn't cover in the articles last week, is so-called "network analysis" where we look at the structure of information flow, human-to-human or user-to-user connections. Here, we will discuss the basic structure of network data as well as how it can be used to tell us something about selective exposure online.

The replication task for this week will give you an example of network data, what it looks like, and how we can manipulate it to speak to some of the questions in the echo chambers literature.

## Essential reading:

-   @conover2011

-   @stier2021

-   @flaxman2016

## Additional reading:

-   @halberstam2016

-   @bakshy2015

-   @mosleh2021

-   @chen2021
