# Week 2: Filter bubbles and echo chambers

This week will be focusing on a substantive problem relating to social media and politics. Namely, we will be thinking about so-called "echo chambers" or "filter bubbles." These refer to platform produced---or algorithmically produced---information environments where the user is exposed only to one sort of political information.

And, normally, this political content is composed of information and opinions agreeable to the user.

Why is this a problem? The argument runs that this is a problem because a healthy society requires citizens to hear, be exposed to, and debate opposing opinions. Without this, societies might become increasingly contentious and polarized.

But how do we study this? And what does computation have to do with it?

## Essential reading:

-   @chen2018

-   @guess2021

-   @levy2021

## Additional reading:

-   @bail2021 (chapters 1-3)
-   @fletcher2021

## Slides

Slides for this week are available [here](https://raw.githack.com/cjbarrie/CS-ED/main/slides/002_echo.html)
