# Course Overview {.unnumbered}

This below gives details of course structure, outcomes, and assessment.

## Learning outcomes {.unnumbered}

This course will give students training in the use of various computational methods in the social sciences. The course will prepare students for dissertation work that uses digital trace data and/or computational methods and will provide hands-on training in the use of the R programming language and (some) Python.

The course will provide a venue for seminar discussion of examples using these methods in the empirical social sciences as well as lectures on the technical and/or statistical dimensions of their application.

## Course structure {.unnumbered}

We will be using this online book for the ten-week course in "Computational Sociology" (PGSP11583). Each chapter contains the readings for that week. The book also includes worksheets with example code for how to conduct some of the text analysis techniques we discuss each week.

Each week (with the partial exception of week 1), we will be discussing, alternately, the substantive and technical dimensions of published research in the empirical social sciences.

## Course theme

In order to discipline the course, I have decided to focus on one theme that is currently making headlines: the political consequences of social media.

With this in mind, every two weeks we will be studying a different phenomenon that has gained media attention: e.g., echo chambers, misinformation, violence.

On alternate weeks, we will discuss how these phenomena have been studied---using both computational and non-computational methods. In the subsequent week, we will then go through some of the technical dimensions of the methods used in the papers we study.

## A Provocation

Unlike other courses you may take, I'm going to be taking a particular position on a question each week during the lecture. I want to invite you to *prove me wrong*. 

I'll be encouraging you to do this at our flash talks (see below) every other week after the lecture has finished. You're also free to air your opinions on Twitter, tag me, and I'll respond. Alternatively, you can write a blog post on a platform such as Medium, Substack, whatever you might choose.

The idea is for this to be an ongoing conversation, debate, and opportunity for us to hear each side out. 

## Course pre-preparation {.unnumbered}

**NOTE**: Before the lecture in Week 2, students should complete two introductory R exercises.

1.  First, you should consult the introduction to file directories and Github [here](https://cjbarrie.github.io/CS-ED/intro.html). This is crucial to properly logging and saving the work you produce.

2.  Second, you should consult the worksheet [here](https://cjbarrie.github.io/CS-ED/intro.html), which is an introduction to setting up and understanding the very basics of working in R. S

3.  Third, Ugur Ozdemir has provided a more comprehensive introductory R course for the Research Training Centre at the University of Edinburgh and you can follow the instructions [here](https://research-training-centre.sps.ed.ac.uk/micro-methods/) to access this.

## Reference sources {.unnumbered}

There are two main reference texts that will be of use during this course:

-   Wickham, Hadley and Garrett Grolemund. R for Data Science: <https://r4ds.had.co.nz/>
-   Salganik, Matt. Bit by Bit: Social Research in the Digital Age: <https://www.bitbybitbook.com/>

## Assessment {.unnumbered}

### Fortnightly worksheets {.unnumbered}

Each fortnight, I will provide you with one worksheet that walks you through how to implement a different computational technique. At the end of these worksheets you will find a set of questions. **You should buddy up with someone else in your class and go through these together.**

This is called "pair programming" and there's a reason we do this. Firstly, coding can be an isolating and difficult thing---it's good to bring a friend along for the ride! Secondly, if there's something you don't know, maybe your buddy will. This saves you both time. Thirdly, your buddy can check your code as you write it, and vice versa. Again, this means both of you are working together to produce and check something as you go along.

At the subsequent week's lecture, I will pick on a pair at random to answer each one of that worksheet's questions (i.e., there is \~1/3 chance you're going to get picked each week). I will ask you to walk us through your code. And remember: it's also fine if you struggled and didn't get to the end! If you encountered an obstacle, we can work through that together. All that matters to me is that you **try**.

### Fortnightly flash talks {.unnumbered}

On the weeks where you are not going to be tasked with a coding assignment, you're not off the hook... I will again be selecting a pair at random (the same as your coding pair) to talk respond to me on the subject of the the readings. I will pick a different pair for each reading (i.e., \~ 1/3 chance again).

I will be taking a position in response to these readings (I won't tell you which one) and I'd like you to try to respond (a bit of devil's advocacy). This is good practice for critically thinking through each side of a question---and the empirical evidence for those respective positions. 

### Final assessment {.unnumbered}

Assessment takes the form of **one** summative assessment. This will be a 4000 word essay on a subject of your choosing (with prior approval by me). For this, you will be required to select from a range of data sources I will provide. You may also suggest your own data source.

You will be asked to: a) formulate a research question; b) use at least one computational technique that we have studied; c) conduct an analysis of the data source you have provided; d) write up the initial findings; and e) outline potential extensions of your analysis.

You will then provide the code you used in reproducible (markdown) format and will be assessed on both the substantive content of your essay contribution (the social science part) as well as your demonstrated competency in coding and text analysis (the computational part).
