# Computational Sociology {.unnumbered}

This is the course book we will be using for Computational Sociology (PGSP11583).

```{r}
print("Computational Sociology")
```

::: {.callout-note appearance="simple"}
The book is a "live" document meaning I will be updating as we progress together through the course.
:::

## Structure

The course is structured of alternating weeks of substantive and technical instruction.

| Week | Focus                                                 | Coding skills                                                                                                                                                         | Workflow skills              | Worksheet |
|------|-------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------|-----------|
| 1    | Intro. Computational Social Science                   | [Introductory exercises](https://cjbarrie.github.io/CS-ED/intror.html) + [RTC Workshop by Ugur Ozdemir](https://research-training-centre.sps.ed.ac.uk/micro-methods/) | Directories, Git, and Github |           |
| 2    | Filter Bubbles and Echo Chambers                      | [R4DS chap.3](https://r4ds.had.co.nz/data-visualisation.html) and [R4DS chap.4](https://r4ds.had.co.nz/workflow-basics.html)                                          |                              |           |
| 3    | Web tracking and Network Analysis                     | [R4DS chap.5](https://r4ds.had.co.nz/transform.html)                                                                                                                  | Markdown                     |           |
| 4    | Misinformation and Fake News                          | [R4DS chap.7](https://r4ds.had.co.nz/exploratory-data-analysis.html)                                                                                                  |                              |           |
| 5    | Linked surveys and Social media analysis              | [R4DS chap.11](https://r4ds.had.co.nz/data-import.html) and [R4DS chap.12](https://r4ds.had.co.nz/tidy-data.html)                                                     | Git and Github               |           |
| 6    | Polarization and Radicalization                       | [R4DS chap.13](https://r4ds.had.co.nz/relational-data.html) and [R4DS chap. 14](https://r4ds.had.co.nz/strings.html)                                                  |                              |           |
| 7    | Online experiments and Bots                           | [R4DS chap.15](https://r4ds.had.co.nz/factors.html) and [R4DS chap. 16](https://r4ds.had.co.nz/dates-and-times.html)                                                  | Markdown                     |           |
| 8    | Violence and Protest                                  | [R4DS chap.18](https://r4ds.had.co.nz/pipes.html) and [R4DS chap. 19](https://r4ds.had.co.nz/functions.html)                                                          |                              |           |
| 9    | Social media tracking and Natural Language Processing | [R4DS chap.20](https://r4ds.had.co.nz/vectors.html) and [R4DS chap. 21](https://r4ds.had.co.nz/iteration.html)                                                        | Database management systems  |           |
| 10   | Guest lecture: TBD                                    |                                                                                                                                                                       |                              |           |

## License

This website is (and will always be) **free to use**, and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) License.
